<?php

namespace KA\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PatientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PatientRepository extends EntityRepository
{
	public function getPatients()
	{
		$query = $this->createQueryBuilder('p')
			->orderBy('p.name', 'ASC')
			->getQuery()
		;
		return $query->getResult();
	}
}
