<?php

namespace KA\PlatformBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * PracticianRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PracticianRepository extends EntityRepository
{
	public function myFindAll()
	{
		return $this
			->createQueryBuilder('p')
			->getQuery()
			->getResult()
		;
	}
	
	public function myFindOne($id)
	{
		$queryBuilder = $this->createQueryBuilder('p');
		$queryBuilder
			->where('p.id = :id')
			->setParameter('id', $id)
		;
		return $queryBuilder
			->getQuery()
			->getResult()
		;
	}
	
	public function getAllPracticians()
	{
		return $this
			->createQueryBuilder('p')
			// ->where('p.getName() != "Admin"')
			// ->orderBy('p.name', 'ASC')
		;
	}
		
}