services:
    ka.registration.form.type:
        class: KA\UserBundle\Form\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: ka_userbundle_registration }